on: push

name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-course 
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}	          
          password: ${{secrets.TOKEN}}	          
          registry: docker.pkg.github.com	          
          repository: rapojj/front-end-tech/frontend-course
          tag_with_sha: true
